"""Native format contracts and readers for the G4 Blender addon."""

from .diagnostics import Diagnostic, DiagnosticReport, NativeFormatError
from .contracts import (
    EffectBinding,
    FidelityState,
    ResourceEvidence,
    ResourceIdentity,
    ShaderParameter,
    ShaderProfile,
)
from .evidence import FormatEvidence, build_format_evidence, discover_format_evidence
from .cfgbin import (
    CfgBinDocument,
    CfgBinEntry,
    CfgBinFormat,
    CfgBinValue,
    CfgBinValueType,
    RdbnpDocument,
    RdbnpField,
    RdbnpList,
    RdbnpRow,
    RdbnpTuple,
    RdbnpType,
    parse_cfgbin,
    parse_cfgbin_file,
)
from .g4mt import (
    G4MTAnimationBank,
    G4MTChannel,
    G4MTClip,
    G4MTHeader,
    G4MTTarget,
    G4MTTargetInfo,
    crc32b,
    parse_g4mt,
    parse_g4mt_file,
)
from .g4ma import (
    G4MAMaterialChannelSummary,
    G4MAMaterialTarget,
    build_g4ma_effect_bindings,
    parse_g4ma,
    parse_g4ma_file,
    resolve_g4ma_material_targets,
    summarize_g4ma_material_channels,
)
from .g4cm import G4CMAnalysis, analyze_g4cm_bank, parse_g4cm, parse_g4cm_file

__all__ = [
    "Diagnostic",
    "DiagnosticReport",
    "NativeFormatError",
    "FidelityState",
    "ResourceEvidence",
    "ResourceIdentity",
    "ShaderParameter",
    "ShaderProfile",
    "FormatEvidence",
    "build_format_evidence",
    "discover_format_evidence",
    "EffectBinding",
    "CfgBinDocument",
    "CfgBinEntry",
    "CfgBinFormat",
    "CfgBinValue",
    "CfgBinValueType",
    "RdbnpDocument",
    "RdbnpField",
    "RdbnpList",
    "RdbnpRow",
    "RdbnpTuple",
    "RdbnpType",
    "parse_cfgbin",
    "parse_cfgbin_file",
    "G4MTAnimationBank",
    "G4MTChannel",
    "G4MTClip",
    "G4MTHeader",
    "G4MTTarget",
    "G4MTTargetInfo",
    "crc32b",
    "parse_g4mt",
    "parse_g4mt_file",
    "G4MAMaterialChannelSummary",
    "G4MAMaterialTarget",
    "build_g4ma_effect_bindings",
    "parse_g4ma",
    "parse_g4ma_file",
    "resolve_g4ma_material_targets",
    "summarize_g4ma_material_channels",
    "G4CMAnalysis",
    "analyze_g4cm_bank",
    "parse_g4cm",
    "parse_g4cm_file",
]
